# Generated by Django 5.2.9 on 2025-12-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('colegio', 'Colegio'), ('fintech', 'Fintech'), ('otro', 'Otro')], default='banco', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('sueldo', 'Sueldo'), ('aguinaldo', 'Aguinaldo'), ('alquiler', 'Alquiler'), ('extra', 'Extraordinario')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deuda', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('prestamo', 'Préstamo'), ('educacion', 'Educación'), ('servicio', 'Servicio'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pago_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('proximo_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('al_dia', 'Al día'), ('en_curso', 'En curso'), ('en_mora', 'En mora'), ('cancelada', 'Cancelada')], default='al_dia', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('cuota_mensual_aprox', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cuotas_restantes', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable'), ('deuda', 'Deuda / cuota'), ('otro', 'Otro')], max_length=20)),
                ('categoria', models.CharField(help_text='Ej: alquiler, comida, colegio, nafta, servicios', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deuda_relacionada', models.ForeignKey(blank=True, help_text='Si este gasto es el pago de una deuda, vinculalo acá.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.deuda')),
            ],
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('deuda', models.ForeignKey(blank=True, help_text='Vincular si corresponde a una deuda específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.deuda')),
            ],
        ),
    ]
