# Generated by Django 5.2.9 on 2025-12-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_deuda_estado_alter_deuda_tipo_deuda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='estado',
            field=models.CharField(choices=[('al_dia', 'Al día'), ('en_curso', 'En curso'), ('en_mora', 'En mora'), ('cancelada', 'Cancelada')], default='al_dia', max_length=20),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='tipo_deuda',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('prestamo', 'Préstamo'), ('educacion', 'Educación'), ('servicio', 'Servicio'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='deuda_relacionada',
            field=models.ForeignKey(blank=True, help_text='Si este gasto es el pago de una deuda, vinculalo acá.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.deuda'),
        ),
        migrations.AlterField(
            model_name='vencimiento',
            name='deuda',
            field=models.ForeignKey(blank=True, help_text='Vincular si corresponde a una deuda específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.deuda'),
        ),
    ]
