# Generated by Django 5.2.9 on 2025-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_deuda_estado_alter_deuda_tipo_deuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='pagado',
            field=models.BooleanField(default=False, help_text='Marcar cuando el gasto ya está pagado.'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Marcar cuando el ingreso ya está cobrado.'),
        ),
    ]
