# Generated by Django 5.2.9 on 2025-12-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_gasto_pagado_ingreso_confirmado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['prioridad', 'entidad__nombre'], 'verbose_name': 'Deuda', 'verbose_name_plural': 'Deudas'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='vencimiento',
            options={'ordering': ['fecha', 'concepto'], 'verbose_name': 'Vencimiento', 'verbose_name_plural': 'Vencimientos'},
        ),
    ]
